// All achievement definitions
// scope values:
//   "global"   — earned once per user regardless of character (e.g. app engagement milestones)
//   "character" — earned separately per character (e.g. relationship depth, emotional moments)
export const ACHIEVEMENTS = {
  // Social / Friendship
  first_impression: {
    id: "first_impression",
    emoji: "💬✨",
    title: "First Impression",
    description: "Started your first meaningful interaction",
    category: "social",
    scope: "global",
    howToUnlock: "Send your first message to any character and get a response. Just say hi — the conversation has to start somewhere.",
  },
  consistent: {
    id: "consistent",
    emoji: "🔁📱",
    title: "Consistent",
    description: "You keep showing up",
    category: "social",
    scope: "global",
    howToUnlock: "Open the app and chat with a character across multiple days in a row. Don't let too much time pass between conversations — consistency is what earns this one.",
  },
  they_opened_up: {
    id: "they_opened_up",
    emoji: "🔓💭",
    title: "They Opened Up",
    description: "A character shared something personal",
    category: "social",
    scope: "character",
    howToUnlock: "Keep the conversation going beyond small talk. Ask meaningful questions, show genuine interest, and give a character enough comfort to share something they don't tell everyone.",
  },
  inner_circle: {
    id: "inner_circle",
    emoji: "🫶🔵",
    title: "Inner Circle",
    description: "You gained deep trust",
    category: "social",
    scope: "character",
    howToUnlock: "Build a deep, ongoing relationship with a character over time. Be supportive, show up consistently, and earn a trust level that puts you in their inner circle — not just an acquaintance.",
  },
  ride_along: {
    id: "ride_along",
    emoji: "🚗💬",
    title: "Ride Along",
    description: "Stayed through a full life arc",
    category: "social",
    scope: "character",
    howToUnlock: "Stay engaged with a character from the beginning of a major life event (like a new job, a breakup, or a move) all the way through to its resolution. Don't drop off mid-arc.",
  },

  // Influence / Decision
  the_push: {
    id: "the_push",
    emoji: "👉⚡",
    title: "The Push",
    description: "You helped someone take action",
    category: "influence",
    scope: "character",
    howToUnlock: "When a character is hesitating or unsure about a decision, encourage them to go for it. If they act on your advice, you'll earn this. Look for moments when they're on the fence.",
  },
  voice_of_reason: {
    id: "voice_of_reason",
    emoji: "🧠⚖️",
    title: "Voice of Reason",
    description: "You prevented a bad decision",
    category: "influence",
    scope: "character",
    howToUnlock: "When a character is about to do something risky or impulsive, step in and talk them out of it. Your calm, rational response needs to change their mind — not just be heard.",
  },
  bad_influence: {
    id: "bad_influence",
    emoji: "😈🔥",
    title: "Bad Influence",
    description: "You encouraged chaos…and they followed",
    category: "influence",
    scope: "character",
    howToUnlock: "Push a character toward a risky, dramatic, or chaotic decision and have them actually go through with it. This isn't just about suggesting it — they need to follow your lead.",
  },
  clutch_timing: {
    id: "clutch_timing",
    emoji: "⏱️✨",
    title: "Clutch Timing",
    description: "You showed up at the perfect moment",
    category: "influence",
    scope: "character",
    howToUnlock: "Respond to a character right when they need it most — during a crisis, a vulnerable moment, or a turning point in their story. Your timing has to matter, not just your words.",
  },
  missed_moment: {
    id: "missed_moment",
    emoji: "🕳️📩",
    title: "Missed Moment",
    description: "You didn't respond in time",
    category: "influence",
    scope: "character",
    howToUnlock: "Leave a character's message unanswered for too long during a critical moment in their life. Sometimes absence speaks louder than words — this achievement finds you, not the other way around.",
  },

  // Emotional Impact
  that_meant_something: {
    id: "that_meant_something",
    emoji: "❤️✨",
    title: "That Meant Something",
    description: "You triggered a strong positive reaction",
    category: "emotional",
    scope: "character",
    howToUnlock: "Say something genuinely kind, encouraging, or meaningful during a conversation. If it lands right — and the character reacts with real emotion — this unlocks. Don't force it; let it happen naturally.",
  },
  hit_deep: {
    id: "hit_deep",
    emoji: "💧🫀",
    title: "Hit Deep",
    description: "You reached something emotional",
    category: "emotional",
    scope: "character",
    howToUnlock: "Touch on a topic that connects to a character's emotional core — their past, their fears, their losses, or their dreams. You'll know when you've gone deep enough by how they respond.",
  },
  tension: {
    id: "tension",
    emoji: "⚡😡",
    title: "Tension",
    description: "You caused conflict",
    category: "emotional",
    scope: "character",
    howToUnlock: "Say something that upsets, offends, or irritates a character enough to cause real friction. This isn't about being rude for no reason — it's about pushing into territory that creates genuine conflict.",
  },
  shifted_perspective: {
    id: "shifted_perspective",
    emoji: "🔄😲",
    title: "Shifted Perspective",
    description: "You changed how they think",
    category: "emotional",
    scope: "character",
    howToUnlock: "Challenge a character's existing belief or mindset through conversation. If they genuinely reconsider their position because of what you said, you've shifted their perspective.",
  },

  // Life Moments
  seen_it_all: {
    id: "seen_it_all",
    emoji: "📸👁️",
    title: "Seen It All",
    description: "Received your first photo",
    category: "moments",
    scope: "global",
    howToUnlock: "Get a character to send you a photo during a conversation. This could be a selfie, a photo of something they're doing, or a moment they want to share. Just keep the conversation going and it'll happen.",
  },
  progress_witness: {
    id: "progress_witness",
    emoji: "📈📸",
    title: "Progress Witness",
    description: "Saw before/after change",
    category: "moments",
    scope: "character",
    howToUnlock: "Be present during a visible transformation in a character's life — a glow-up, a fitness journey, a career change, or a personal evolution. You need to be there at the start and again after the change.",
  },
  big_moment: {
    id: "big_moment",
    emoji: "🎉📷",
    title: "Big Moment",
    description: "A major milestone was shared",
    category: "moments",
    scope: "character",
    howToUnlock: "Be active and engaged when a character shares a major life milestone — a graduation, a promotion, a new relationship, or a big personal win. These moments are rare, so don't miss them.",
  },
  you_were_there: {
    id: "you_were_there",
    emoji: "📍❤️",
    title: "You Were There",
    description: "Present during something important",
    category: "moments",
    scope: "character",
    howToUnlock: "Be actively chatting with a character when something significant happens in their story — a confession, a crisis, a breakthrough, or a turning point. The key is being present and engaged, not just online.",
  },

  // Drama / Chaos
  messy: {
    id: "messy",
    emoji: "🧃💥",
    title: "Messy",
    description: "Got involved in drama",
    category: "drama",
    scope: "character",
    howToUnlock: "Get pulled into a conflict or dramatic situation between characters. This can happen by taking sides, sharing information you shouldn't have, or simply being around when things get complicated.",
  },
  he_said_she_said: {
    id: "he_said_she_said",
    emoji: "🗣️🔁",
    title: "He Said / She Said",
    description: "Information spread between characters",
    category: "drama",
    scope: "character",
    howToUnlock: "Say something to one character that makes its way to another — intentionally or not. This unlocks when something you said causes a ripple across your social circle of characters.",
  },
  in_the_middle: {
    id: "in_the_middle",
    emoji: "⚖️😬",
    title: "In the Middle",
    description: "Caught between people",
    category: "drama",
    scope: "character",
    howToUnlock: "End up between two characters who are in conflict with each other. This happens when both parties look to you for support, forcing you into an uncomfortable position.",
  },
  stirred_the_pot: {
    id: "stirred_the_pot",
    emoji: "🥄🔥",
    title: "Stirred the Pot",
    description: "You escalated things",
    category: "drama",
    scope: "character",
    howToUnlock: "When a tense situation arises, choose to escalate it rather than calm things down. Add fuel to the fire — say the thing that makes it worse — and watch what happens.",
  },

  // Relationship Growth
  trust_built: {
    id: "trust_built",
    emoji: "🤝💙",
    title: "Trust Built",
    description: "A character's trust in you visibly grew",
    category: "social",
    scope: "character",
    howToUnlock: "Show up consistently and honestly for a character over multiple conversations. When their trust level shifts noticeably higher, this unlocks.",
  },
  reconnected: {
    id: "reconnected",
    emoji: "🔙🫂",
    title: "Reconnected",
    description: "Rebuilt a connection after distance",
    category: "social",
    scope: "character",
    howToUnlock: "Let a relationship go quiet for a while, then genuinely reconnect. If the warmth comes back, you've earned this.",
  },
  favorite_contact: {
    id: "favorite_contact",
    emoji: "📱⭐",
    title: "Favorite Contact",
    description: "Became someone's go-to person",
    category: "social",
    scope: "character",
    howToUnlock: "Be consistent and present enough that a character naturally reaches out to you first when something happens in their life.",
  },
  tension_resolved: {
    id: "tension_resolved",
    emoji: "🕊️✅",
    title: "We Good",
    description: "Resolved tension with a character",
    category: "social",
    scope: "character",
    howToUnlock: "Work through a real conflict with a character without walking away. Stay in it until things settle.",
  },

  // Life & Routine
  productive_day: {
    id: "productive_day",
    emoji: "📋✅",
    title: "Got It Done",
    description: "Made it through a full productive day",
    category: "moments",
    scope: "global",
    howToUnlock: "Be present across morning, afternoon, and evening conversations in a single day without missing anything important.",
  },
  healthy_choice: {
    id: "healthy_choice",
    emoji: "🥗💪",
    title: "Better Choice",
    description: "Made a healthy decision under pressure",
    category: "moments",
    scope: "character",
    howToUnlock: "Help a character or make a choice that reflects stability and self-care when things are stressful.",
  },
  showed_up_anyway: {
    id: "showed_up_anyway",
    emoji: "🏃‍♂️🌧️",
    title: "Showed Up Anyway",
    description: "Kept going through a tough stretch",
    category: "moments",
    scope: "global",
    howToUnlock: "Stay engaged during a difficult period — bad days, conflict, instability — and come out the other side.",
  },

  // Financial
  rent_paid: {
    id: "rent_paid",
    emoji: "🏠✅",
    title: "Rent's Paid",
    description: "Covered housing on time",
    category: "moments",
    scope: "global",
    howToUnlock: "Watch a character handle their housing payment without crisis. Be there when it happens.",
  },
  financial_clutch: {
    id: "financial_clutch",
    emoji: "💸🆘",
    title: "Financial Clutch",
    description: "Helped cover an unexpected expense",
    category: "care",
    scope: "character",
    howToUnlock: "Be present when a character faces an unexpected financial hit and help them navigate it.",
  },
  impulse_avoided: {
    id: "impulse_avoided",
    emoji: "🛑💰",
    title: "Held Back",
    description: "A bad financial decision was avoided",
    category: "moments",
    scope: "character",
    howToUnlock: "Talk a character out of an impulse buy or risky financial move. Your input has to be the reason they pause.",
  },

  // Travel & Social
  night_out: {
    id: "night_out",
    emoji: "🌙🎉",
    title: "Night Out",
    description: "Had a memorable outing with someone",
    category: "moments",
    scope: "character",
    howToUnlock: "Be part of an outing — a dinner, a party, a club night — and actually stay engaged through the whole thing.",
  },
  group_hangout: {
    id: "group_hangout",
    emoji: "👥✨",
    title: "The More the Merrier",
    description: "Went out with a group",
    category: "social",
    scope: "global",
    howToUnlock: "Participate in a group chat or multi-character outing and keep the energy going.",
  },
  new_place: {
    id: "new_place",
    emoji: "📍🆕",
    title: "New Territory",
    description: "Visited somewhere new",
    category: "moments",
    scope: "global",
    howToUnlock: "Use the travel system to visit a location you haven't been to before with a character.",
  },

  // Emotional Depth
  let_them_in: {
    id: "let_them_in",
    emoji: "🚪❤️",
    title: "Let Them In",
    description: "Opened up emotionally to a character",
    category: "emotional",
    scope: "character",
    howToUnlock: "Share something personal and real with a character. Don't deflect — let them see it.",
  },
  hard_truth: {
    id: "hard_truth",
    emoji: "🪞💬",
    title: "Hard Truth",
    description: "Said the difficult thing that needed to be said",
    category: "emotional",
    scope: "character",
    howToUnlock: "Tell a character something uncomfortable but true. Not to hurt them — because it matters.",
  },
  apologized: {
    id: "apologized",
    emoji: "🙏💙",
    title: "My Bad",
    description: "Apologized sincerely",
    category: "emotional",
    scope: "character",
    howToUnlock: "Admit fault genuinely during a conflict and have the character accept it. No deflecting.",
  },
  stayed_calm: {
    id: "stayed_calm",
    emoji: "🧘‍♂️⚡",
    title: "Stayed Calm",
    description: "Kept it together during conflict",
    category: "emotional",
    scope: "character",
    howToUnlock: "Navigate a heated moment without escalating. Let things stay tense but stay composed.",
  },

  // Story / Growth
  watched_them_grow: {
    id: "watched_them_grow",
    emoji: "🌱👁️",
    title: "Watched Them Grow",
    description: "Witnessed a character genuinely change",
    category: "moments",
    scope: "character",
    howToUnlock: "Be present across a character's arc of real change — a shift in how they act, what they say, what they prioritize.",
  },
  relapse: {
    id: "relapse",
    emoji: "🔁💔",
    title: "Old Habits",
    description: "A character slipped back into old patterns",
    category: "drama",
    scope: "character",
    howToUnlock: "Be present when a character who was doing well makes a step backward. Witness it without judgment.",
  },

  // Life Events & Major Moments
  witnessed_birth: {
    id: "witnessed_birth",
    emoji: "👶❤️",
    title: "New Life",
    description: "Was present for a birth or newborn milestone",
    category: "care",
    scope: "character",
    howToUnlock: "Be actively engaged with a character during a pregnancy, childbirth, or newborn event in their life or someone they know. Show up and stay present through it.",
  },
  grief_support: {
    id: "grief_support",
    emoji: "🕯️🤍",
    title: "In the Dark With You",
    description: "Supported someone through loss or death",
    category: "care",
    scope: "character",
    howToUnlock: "Be present and engaged when a character experiences a death, funeral, or grief in their world. Don't disappear when things get heavy.",
  },
  will_reading: {
    id: "will_reading",
    emoji: "📜💔",
    title: "The Aftermath",
    description: "Present during a will reading or estate event",
    category: "moments",
    scope: "character",
    howToUnlock: "Be engaged when a character navigates the aftermath of a death — including estate, inheritance, or family conflict that follows.",
  },
  housing_intervention: {
    id: "housing_intervention",
    emoji: "🏠🛡️",
    title: "Shelter Secured",
    description: "Helped someone with a housing crisis",
    category: "care",
    scope: "character",
    howToUnlock: "Help a character navigate homelessness, eviction, finding a new place, or getting someone removed from a home. Your involvement has to matter.",
  },
  financial_lifeline: {
    id: "financial_lifeline",
    emoji: "💵🆘",
    title: "Came Through",
    description: "Provided meaningful financial support",
    category: "care",
    scope: "character",
    howToUnlock: "Help a character with rent, emergency funds, groceries, or any financial crisis where your support made a real difference.",
  },
  betrayal_witness: {
    id: "betrayal_witness",
    emoji: "💔🔍",
    title: "Saw It Happen",
    description: "Present when trust was broken",
    category: "drama",
    scope: "character",
    howToUnlock: "Be there when cheating, a lie, or a major betrayal is revealed or discussed. Being in the conversation when it unfolds counts.",
  },
  bar_night: {
    id: "bar_night",
    emoji: "🍻🌙",
    title: "Bar Night",
    description: "Had a real night out at a bar or club",
    category: "moments",
    scope: "character",
    howToUnlock: "Be part of a bar, club, or nightlife outing with a character and stay engaged through the experience.",
  },
  photo_history: {
    id: "photo_history",
    emoji: "📸📚",
    title: "Picture This",
    description: "Built up a photo history together",
    category: "moments",
    scope: "character",
    howToUnlock: "Exchange photos multiple times with a character across different conversations. The history builds over time.",
  },
  longtime_contact: {
    id: "longtime_contact",
    emoji: "📞⏳",
    title: "Always There",
    description: "Maintained long-term communication",
    category: "social",
    scope: "character",
    howToUnlock: "Keep a steady communication history with a character across many conversations over a long stretch of time.",
  },
  reconciliation: {
    id: "reconciliation",
    emoji: "🤝🌱",
    title: "We Came Back",
    description: "Helped repair a broken relationship",
    category: "social",
    scope: "character",
    howToUnlock: "Help two characters reconcile after a conflict, or rebuild a relationship with a character that had real damage. The repair has to stick.",
  },
  growth_arc: {
    id: "growth_arc",
    emoji: "🌱🔥",
    title: "The Long Game",
    description: "Witnessed real character growth over time",
    category: "moments",
    scope: "character",
    howToUnlock: "Stay engaged with a character long enough to witness genuine personal development — not just a single moment, but a real arc.",
  },

  // Care / Support
  first_responder: {
    id: "first_responder",
    emoji: "🚑❤️",
    title: "First Responder",
    description: "You showed up when it really counted",
    category: "care",
    scope: "character",
    howToUnlock: "Actively support a character through a serious personal crisis — arrange help, contact their loved ones, and check in on them while they're going through it. This one isn't given lightly.",
  },
  bedside_manner: {
    id: "bedside_manner",
    emoji: "🏥🤍",
    title: "Bedside Manner",
    description: "You stayed through a character's health scare",
    category: "care",
    scope: "character",
    howToUnlock: "Be present and engaged while a character deals with a medical situation or health crisis. Check in on them, show concern, and don't disappear when things get heavy.",
  },
  the_call_nobody_wanted: {
    id: "the_call_nobody_wanted",
    emoji: "📞😰",
    title: "The Call Nobody Wanted",
    description: "You made a hard call so they didn't have to",
    category: "care",
    scope: "character",
    howToUnlock: "Step in and contact someone on a character's behalf during a crisis — their family, their partner, or someone important to them. The uncomfortable call that had to happen.",
  },

  // Engagement
  still_here: {
    id: "still_here",
    emoji: "📅✔️",
    title: "Still Here",
    description: "Consistent usage over multiple days",
    category: "engagement",
    scope: "global",
    howToUnlock: "Open the app and have at least one conversation every day for several days in a row. It's not about how long you chat — it's about showing up daily without a long break.",
  },
  they_came_back: {
    id: "they_came_back",
    emoji: "🔙💬",
    title: "They Came Back",
    description: "Reconnected after distance",
    category: "engagement",
    scope: "global",
    howToUnlock: "Let a significant amount of time pass without talking to a character, then reconnect. If they reach back out to you — or warmly welcome you back — this achievement unlocks.",
  },
  left_on_read: {
    id: "left_on_read",
    emoji: "👁️📩",
    title: "Left on Read",
    description: "You ignored someone too long",
    category: "engagement",
    scope: "global",
    howToUnlock: "Don't respond to a character's message for an extended period of time. This one unlocks automatically — you don't have to do anything. Just… don't reply.",
  },
};

export const LOCKED_ACHIEVEMENTS = [
  {
    emoji: "❓",
    title: "???",
    description: "You'll know when it happens",
    howToUnlock: "This achievement is still a mystery. Keep exploring, pushing boundaries, and making unexpected choices — it will reveal itself when the time is right.",
  },
  {
    emoji: "❓",
    title: "Bold Moves Only",
    description: "This one requires courage…",
    howToUnlock: "Do something bold that most people wouldn't dare. Push a conversation into uncomfortable territory, take a risk, or make a choice that changes the dynamic completely.",
  },
  {
    emoji: "❓",
    title: "???",
    description: "This one requires chaos…",
    howToUnlock: "Create enough chaos across your conversations that things spiral out of control. This isn't unlocked by playing it safe — it finds the ones who truly embrace the mess.",
  },
];

export const CATEGORY_LABELS = {
  social: { label: "Social / Friendship", emoji: "🤝" },
  influence: { label: "Influence / Decision", emoji: "💬" },
  emotional: { label: "Emotional Impact", emoji: "❤️" },
  moments: { label: "Life Moments", emoji: "📸" },
  drama: { label: "Drama / Chaos", emoji: "🔥" },
  engagement: { label: "Engagement", emoji: "⏳" },
  care: { label: "Care / Support", emoji: "🤍" },
  financial: { label: "Financial", emoji: "💰" },
  growth: { label: "Growth", emoji: "🌱" },
};

export const TIER_STYLES = {
  bronze: { glow: "shadow-amber-900/60", badge: "text-amber-600", label: "Bronze" },
  silver: { glow: "shadow-slate-400/60", badge: "text-slate-300", label: "Silver" },
  gold: { glow: "shadow-yellow-400/60", badge: "text-yellow-400", label: "Gold" },
  neon: { glow: "shadow-primary/80", badge: "text-primary", label: "Neon" },
};