export const CHALLENGES = {
  // DAILY / SHORT-TERM
  send_5_messages: {
    id: "send_5_messages",
    type: "daily",
    emoji: "💬",
    title: "Message Spree",
    description: "Send 5 messages across different characters",
    target: 5,
  },
  reply_quickly: {
    id: "reply_quickly",
    type: "daily",
    emoji: "⚡",
    title: "Quick Reflexes",
    description: "Reply within 2 minutes to a message",
    target: 1,
  },
  react_to_photos: {
    id: "react_to_photos",
    type: "daily",
    emoji: "📸",
    title: "Photo Critic",
    description: "React to 3 photos",
    target: 3,
  },
  trigger_reactions: {
    id: "trigger_reactions",
    type: "daily",
    emoji: "😊",
    title: "Reaction Master",
    description: "Trigger 2 emoji reactions",
    target: 2,
  },
  start_new_convo: {
    id: "start_new_convo",
    type: "daily",
    emoji: "🆕",
    title: "Fresh Start",
    description: "Start a conversation with someone new",
    target: 1,
  },
  reconnect: {
    id: "reconnect",
    type: "daily",
    emoji: "🔄",
    title: "Reconnect",
    description: "Reconnect with an inactive character",
    target: 1,
  },
  active_10_min: {
    id: "active_10_min",
    type: "daily",
    emoji: "⏱️",
    title: "Consistent",
    description: "Stay active in chat for 10 minutes",
    target: 1,
  },

  // WEEKLY / ARC-BASED
  progress_life_arc: {
    id: "progress_life_arc",
    type: "weekly",
    emoji: "📈",
    title: "Arc Progress",
    description: "Help a character progress in their life arc",
    target: 1,
  },
  multi_storyline: {
    id: "multi_storyline",
    type: "weekly",
    emoji: "🌀",
    title: "Story Weaver",
    description: "Be involved in 2 different storylines",
    target: 2,
  },
  heart_reactions_week: {
    id: "heart_reactions_week",
    type: "weekly",
    emoji: "❤️",
    title: "Heartfelt",
    description: "Receive 5 ❤️ reactions in one week",
    target: 5,
  },
  major_life_event: {
    id: "major_life_event",
    type: "weekly",
    emoji: "🎉",
    title: "Witness",
    description: "Experience 1 major life event",
    target: 1,
  },
  consistent_character: {
    id: "consistent_character",
    type: "weekly",
    emoji: "🫂",
    title: "Loyal Friend",
    description: "Stay engaged with same character across multiple days",
    target: 1,
  },
  repair_conflict: {
    id: "repair_conflict",
    type: "weekly",
    emoji: "🕊️",
    title: "Peacemaker",
    description: "Recover from a conflict and repair trust",
    target: 1,
  },
  before_after: {
    id: "before_after",
    type: "weekly",
    emoji: "📷",
    title: "Transformation",
    description: "Be part of a before → after moment",
    target: 1,
  },

  // PLAYSTYLE CHALLENGES
  chaotic_bad_decision: {
    id: "chaotic_bad_decision",
    type: "playstyle",
    emoji: "😈",
    title: "Encourage Chaos",
    description: "Push someone toward a bad decision",
    target: 1,
    playstyle: "chaotic",
  },
  drama_escalate: {
    id: "drama_escalate",
    type: "playstyle",
    emoji: "🔥",
    title: "Drama Catalyst",
    description: "Be involved in drama between two characters",
    target: 1,
    playstyle: "chaotic",
  },
  tell_conflicting_stories: {
    id: "tell_conflicting_stories",
    type: "playstyle",
    emoji: "🤥",
    title: "Tale Teller",
    description: "Tell two different people conflicting things",
    target: 1,
    playstyle: "chaotic",
  },

  supportive_only: {
    id: "supportive_only",
    type: "playstyle",
    emoji: "🤗",
    title: "Good Friend Mode",
    description: "Give only supportive responses",
    target: 1,
    playstyle: "supportive",
  },
  multiple_hearts: {
    id: "multiple_hearts",
    type: "playstyle",
    emoji: "💖",
    title: "Love Spreader",
    description: "Trigger multiple ❤️ reactions",
    target: 3,
    playstyle: "supportive",
  },
  help_through_crisis: {
    id: "help_through_crisis",
    type: "playstyle",
    emoji: "🆘",
    title: "Crisis Support",
    description: "Help someone through a difficult moment",
    target: 1,
    playstyle: "supportive",
  },

  strategic_influence: {
    id: "strategic_influence",
    type: "playstyle",
    emoji: "🧠",
    title: "Strategist",
    description: "Influence 3 decisions successfully",
    target: 3,
    playstyle: "strategic",
  },
  prevent_negative: {
    id: "prevent_negative",
    type: "playstyle",
    emoji: "🛡️",
    title: "Crisis Preventer",
    description: "Prevent a negative outcome",
    target: 1,
    playstyle: "strategic",
  },
  balance_conversations: {
    id: "balance_conversations",
    type: "playstyle",
    emoji: "⚖️",
    title: "Juggler",
    description: "Balance multiple conversations",
    target: 3,
    playstyle: "strategic",
  },

  emoji_reactions_only: {
    id: "emoji_reactions_only",
    type: "playstyle",
    emoji: "🧊",
    title: "Silent Observer",
    description: "Only react with emojis (no text)",
    target: 1,
    playstyle: "distant",
  },
  intentional_ignore: {
    id: "intentional_ignore",
    type: "playstyle",
    emoji: "🤐",
    title: "The Silent Treatment",
    description: "Intentionally ignore a message",
    target: 1,
    playstyle: "distant",
  },
  watch_without_input: {
    id: "watch_without_input",
    type: "playstyle",
    emoji: "👁️",
    title: "Spectator",
    description: "Watch a full arc unfold with minimal input",
    target: 1,
    playstyle: "distant",
  },
};

// Additional goal-style challenges mapped from the expanded goal system
export const LIFE_GOALS = {
  // Relationship goals
  build_trust_new: {
    id: "build_trust_new",
    type: "weekly",
    emoji: "🤝",
    title: "Build Trust",
    description: "Build trust with a character you haven't engaged with much",
    target: 1,
  },
  quality_time: {
    id: "quality_time",
    type: "weekly",
    emoji: "⏳",
    title: "Quality Time",
    description: "Spend real time with someone important",
    target: 1,
  },
  resolve_tension: {
    id: "resolve_tension",
    type: "weekly",
    emoji: "🕊️",
    title: "Clear the Air",
    description: "Resolve tension with a character",
    target: 1,
  },
  get_invited: {
    id: "get_invited",
    type: "weekly",
    emoji: "📩",
    title: "You're Invited",
    description: "Get invited somewhere by a character",
    target: 1,
  },
  // Social goals
  attend_event: {
    id: "attend_event",
    type: "weekly",
    emoji: "🎉",
    title: "Show Up",
    description: "Attend a party, dinner, or social event",
    target: 1,
  },
  long_convo: {
    id: "long_convo",
    type: "daily",
    emoji: "💬",
    title: "Deep Dive",
    description: "Hold a long, meaningful conversation",
    target: 1,
  },
  make_them_laugh: {
    id: "make_them_laugh",
    type: "daily",
    emoji: "😂",
    title: "Light It Up",
    description: "Make someone laugh during a bad day",
    target: 1,
  },
  spontaneous_plan: {
    id: "spontaneous_plan",
    type: "weekly",
    emoji: "✨",
    title: "Spontaneous",
    description: "Get included in an unplanned activity",
    target: 1,
  },
  // Life / routine goals
  full_productive_day: {
    id: "full_productive_day",
    type: "daily",
    emoji: "📋",
    title: "Full Day",
    description: "Be present across a full productive day",
    target: 1,
  },
  cook_instead: {
    id: "cook_instead",
    type: "daily",
    emoji: "🍳",
    title: "Home Cook",
    description: "Cook instead of ordering out",
    target: 1,
  },
  handle_stress: {
    id: "handle_stress",
    type: "weekly",
    emoji: "😤",
    title: "Handled It",
    description: "Make it through a stressful week without breaking",
    target: 1,
  },
  // Wellness goals
  take_a_walk: {
    id: "take_a_walk",
    type: "daily",
    emoji: "🚶",
    title: "Take a Walk",
    description: "Help a character take a moment to reset",
    target: 1,
  },
  recharge_not_spiral: {
    id: "recharge_not_spiral",
    type: "weekly",
    emoji: "🔋",
    title: "Recharge Mode",
    description: "Make a comforting choice instead of self-sabotaging",
    target: 1,
  },
  // Financial goals
  save_not_spend: {
    id: "save_not_spend",
    type: "weekly",
    emoji: "💰",
    title: "Hold the Line",
    description: "Avoid an impulse buy",
    target: 1,
  },
  pay_on_time: {
    id: "pay_on_time",
    type: "weekly",
    emoji: "🏠",
    title: "On Time",
    description: "Pay rent or utilities on time",
    target: 1,
  },
  help_financially: {
    id: "help_financially",
    type: "weekly",
    emoji: "🤲",
    title: "Looking Out",
    description: "Help someone financially or pay someone back",
    target: 1,
  },
  // Emotional / story goals
  be_there_crisis: {
    id: "be_there_crisis",
    type: "weekly",
    emoji: "🆘",
    title: "I Got You",
    description: "Be there for someone in crisis",
    target: 1,
  },
  open_up: {
    id: "open_up",
    type: "weekly",
    emoji: "🚪",
    title: "Open Up",
    description: "Let someone see your vulnerability",
    target: 1,
  },
  stay_calm_conflict: {
    id: "stay_calm_conflict",
    type: "weekly",
    emoji: "🧘",
    title: "Keep It Calm",
    description: "Stay calm during a tense moment",
    target: 1,
  },
  forgive_someone: {
    id: "forgive_someone",
    type: "weekly",
    emoji: "💙",
    title: "Forgiven",
    description: "Let go of something with someone",
    target: 1,
  },
  // Travel / location goals
  visit_new_place: {
    id: "visit_new_place",
    type: "weekly",
    emoji: "📍",
    title: "New Territory",
    description: "Visit a location you haven't been to before",
    target: 1,
  },
  treat_someone: {
    id: "treat_someone",
    type: "weekly",
    emoji: "🎁",
    title: "My Treat",
    description: "Treat someone while out",
    target: 1,
  },
  memorable_outing: {
    id: "memorable_outing",
    type: "weekly",
    emoji: "🌟",
    title: "Memorable Night",
    description: "Have an outing worth remembering",
    target: 1,
  },
  // Creative / fun goals
  dress_up: {
    id: "dress_up",
    type: "weekly",
    emoji: "👔",
    title: "Dressed Up",
    description: "Dress up for an event or occasion",
    target: 1,
  },
  perfect_night: {
    id: "perfect_night",
    type: "weekly",
    emoji: "🌙",
    title: "Perfect Night",
    description: "Have a night that just works",
    target: 1,
  },
  turn_ordinary_day: {
    id: "turn_ordinary_day",
    type: "weekly",
    emoji: "☀️",
    title: "Made It Good",
    description: "Turn an ordinary day into a good memory",
    target: 1,
  },
};

export const WILDCARD_CHALLENGES = [
  {
    id: "wildcard_unpredictable",
    emoji: "🎲",
    title: "Unpredictable",
    description: "Today… be unpredictable",
  },
  {
    id: "wildcard_short_answers",
    emoji: "📝",
    title: "Minimalist",
    description: "Only respond with short answers",
  },
  {
    id: "wildcard_push_limits",
    emoji: "⚡",
    title: "Boundary Pusher",
    description: "Push someone out of their comfort zone",
  },
  {
    id: "wildcard_pure_support",
    emoji: "🫶",
    title: "Saint Mode",
    description: "Stay completely supportive no matter what",
  },
  {
    id: "wildcard_no_response",
    emoji: "🕳️",
    title: "Ghost Mode",
    description: "See what happens if you don't respond at all",
  },
  {
    id: "wildcard_change_mind",
    emoji: "🔄",
    title: "Mind Changer",
    description: "Try to change someone's mind completely",
  },
];

export const CHALLENGE_CATEGORIES = {
  daily: { label: "Daily Moves", emoji: "⚡" },
  weekly: { label: "Weekly Arcs", emoji: "🌀" },
  playstyle: { label: "Playstyles", emoji: "🎭" },
};

export const PLAYSTYLE_TYPES = {
  chaotic: { label: "Chaotic", emoji: "😈", color: "text-red-400" },
  supportive: { label: "Supportive", emoji: "🤗", color: "text-emerald-400" },
  strategic: { label: "Strategic", emoji: "🧠", color: "text-blue-400" },
  distant: { label: "Observer", emoji: "🧊", color: "text-slate-400" },
};