/**
 * worldPhoneActionHandler.js
 *
 * Handles the character_action path for World Phone sends.
 * Called from Chat.jsx when a character's LLM response CLAIMS it texted/called someone.
 *
 * Contract:
 * - Sends the actual World Phone message (creates DB record)
 * - If send fails: strips the false claim from responseText
 * - If send succeeds: strips any fabricated summary of what the recipient supposedly said back
 *   (Character B's REAL response is generated by the backend, visible in World Contacts)
 *
 * Returns: { responseText, worldPhoneSendResult }
 */

import { detectCharacterWorldPhoneAction, stripFabricatedReplyFromResponse } from "@/lib/worldPhoneIntentDetector";
import { base44 } from "@/api/base44Client";

export async function handleCharacterWorldPhoneAction({
  responseText,
  character,
  characterId,
  conversationId,
  ownerEmail,
}) {
  if (!responseText) return { responseText, worldPhoneSendResult: null };

  const charActionIntent = detectCharacterWorldPhoneAction(responseText, character.name);
  if (!charActionIntent) return { responseText, worldPhoneSendResult: null };

  console.log('[WorldPhone] character-action intent detected:', charActionIntent);

  // If the character claimed they sent something but no explicit message content was detected,
  // use the character's own response text as context so the backend can generate the message.
  const messageToSend = charActionIntent.message || responseText;

  const charActionResult = await base44.functions.invoke('sendWorldPhoneMessage', {
    sender_character_id: characterId,
    recipient_identifier: charActionIntent.recipient,
    requested_message: messageToSend,
    source: 'character_action',
    current_conversation_id: conversationId,
    owner_email: ownerEmail,
  }).catch(err => ({ data: { success: false, error: err.message } }));

  const charActionData = charActionResult?.data;

  if (!charActionData?.success) {
    // Send failed — strip the false claim entirely
    console.warn('[WorldPhone] character-action send failed — removing false claim:', charActionData?.error);
    const cleaned = responseText
      .replace(/I\s+(just\s+)?(texted|called|messaged|sent\s+\w+\s+a\s+(text|message|call))\s+[A-Z][a-z]+[^.!?]*[.!?]/gi, '')
      .replace(/\s{2,}/g, ' ')
      .trim();
    return {
      responseText: cleaned || '...',
      worldPhoneSendResult: null,
    };
  }

  // Send succeeded — strip any fabricated summary of what Character B said back
  const stripped = stripFabricatedReplyFromResponse(responseText);
  if (stripped !== responseText) {
    console.log('[WorldPhone] character-action succeeded — stripped fabricated reply summary from response');
  }

  return {
    responseText: stripped,
    worldPhoneSendResult: charActionResult,
  };
}