/**
 * worldPhoneActionHandler.js
 *
 * Handles World Phone character communication paths — NOT appointment/travel/movement.
 *
 * This is a social behavior system. It answers:
 * "Did the character initiate real communication, and does it appear in World Phone?"
 *
 * Path 1 — Past-tense claims ("I texted her", "I called him")
 *   → Back-fill the real World Phone message.
 *   → If send fails: strip the false claim from responseText so the character
 *     doesn't reference communication that has no World Phone record.
 *
 * Path 2 — Proactive outreach ("I'll text her", "I'll call him")
 *   → Send the World Phone message immediately.
 *   → If recipient is unresolved: log and drop silently. Do NOT create a fake
 *     meeting, travel commitment, or appointment record. That is a different system.
 *   → If send succeeds: strip any fabricated summary of what the recipient
 *     supposedly said back (their real response comes from their own LLM call).
 *
 * This handler MUST NOT:
 * - create CharacterCommitment records
 * - store recipient names in destination fields
 * - interact with travel or movement logic
 * - use appointment or meeting commitment types
 *
 * Returns: { responseText, worldPhoneSendResult, proactiveSendResult }
 */

import { detectCharacterWorldPhoneAction, detectCharacterProactiveOutreach, stripFabricatedReplyFromResponse } from "@/lib/worldPhoneIntentDetector";
import { base44 } from "@/api/base44Client";

/**
 * Resolves a pronoun to a real recipient name from recent conversation messages.
 * Scans backwards — most recent mention of a known contact wins.
 */
function resolvePronounRecipient(character, recentMessages) {
  const knownNames = [
    ...(character?.fictional_relationships || []).map(r => r.person_name).filter(Boolean),
    ...(character?.family_members || []).map(f => f.name).filter(Boolean),
  ];
  if (!knownNames.length || !recentMessages?.length) return null;
  for (let i = recentMessages.length - 1; i >= 0; i--) {
    const content = (recentMessages[i]?.content || '').toLowerCase();
    for (const name of knownNames) {
      if (name.length > 2 && content.includes(name.toLowerCase())) {
        return name;
      }
    }
  }
  return null;
}

export async function handleCharacterWorldPhoneAction({
  responseText,
  character,
  characterId,
  conversationId,
  ownerEmail,
  recentMessages,
}) {
  if (!responseText) return { responseText, worldPhoneSendResult: null, proactiveSendResult: null };

  let modifiedResponseText = responseText;
  let worldPhoneSendResult = null;
  let proactiveSendResult = null;

  // ── PATH 1: PAST-TENSE CLAIMS ─────────────────────────────────────────────
  // Character claims communication already happened. Back-fill the World Phone record
  // or strip the false claim if the send fails.
  const pastTenseAction = detectCharacterWorldPhoneAction(responseText, character.name);

  if (pastTenseAction) {
    console.log('[WorldPhone] past-tense claim detected:', pastTenseAction);

    const result = await base44.functions.invoke('sendWorldPhoneMessage', {
      sender_character_id: characterId,
      recipient_identifier: pastTenseAction.recipient,
      requested_message: pastTenseAction.message || responseText,
      source: 'character_action',
      current_conversation_id: conversationId,
      owner_email: ownerEmail,
    }).catch(err => ({ data: { success: false, error: err.message } }));

    worldPhoneSendResult = result;
    const data = result?.data;

    if (!data?.success) {
      // No World Phone record — remove the false claim so it doesn't stand unsupported
      console.warn('[WorldPhone] past-tense send failed — stripping false claim:', data?.error);
      modifiedResponseText = responseText
        .replace(/I\s+(just\s+)?(texted|called|messaged|sent\s+\w+\s+a\s+(text|message|call))\s+[A-Z][a-z]+[^.!?]*[.!?]/gi, '')
        .replace(/\s{2,}/g, ' ')
        .trim() || '...';
    } else {
      // Strip any fabricated summary of what the recipient supposedly replied —
      // their real response is generated by their own LLM pipeline
      const stripped = stripFabricatedReplyFromResponse(modifiedResponseText);
      if (stripped !== modifiedResponseText) {
        console.log('[WorldPhone] past-tense: stripped fabricated reply summary');
      }
      modifiedResponseText = stripped;
    }
  }

  // ── PATH 2: PROACTIVE OUTREACH ────────────────────────────────────────────
  // Character says they will contact someone. This is social/emotional behavior —
  // not an appointment, not travel, not movement. Send through World Phone now.
  const outreach = detectCharacterProactiveOutreach(modifiedResponseText, character.name);

  if (outreach) {
    let recipient = outreach.recipient;

    // Resolve pronoun to actual name if needed
    if (!recipient && outreach.hasPronoun) {
      recipient = resolvePronounRecipient(character, recentMessages);
      if (recipient) {
        console.log(`[WorldPhone] pronoun resolved to "${recipient}" from conversation context`);
      }
    }

    if (recipient) {
      console.log(`[WorldPhone] proactive outreach: "${character.name}" → "${recipient}"`);

      const result = await base44.functions.invoke('sendWorldPhoneMessage', {
        sender_character_id: characterId,
        recipient_identifier: recipient,
        requested_message: null,
        user_instruction_context: outreach.topic || `${character.name} is reaching out to ${recipient}`,
        source: 'character_action',
        current_conversation_id: conversationId,
        owner_email: ownerEmail,
        generate_recipient_response: true,
      }).catch(err => ({ data: { success: false, error: err.message } }));

      proactiveSendResult = result;
      const data = result?.data;

      if (data?.success) {
        console.log(`[WorldPhone] proactive send complete: "${character.name}" → "${recipient}" | msg=${data.message_id}`);
        // Strip fabricated reply summary if present
        modifiedResponseText = stripFabricatedReplyFromResponse(modifiedResponseText);
      } else {
        // Send failed — log only. Do NOT create a meeting, travel commitment,
        // appointment record, or any other cross-system artifact.
        console.warn(`[WorldPhone] proactive send failed: ${data?.error}`);
      }
    } else {
      // Recipient could not be resolved — log only. This is a communication system.
      // Unresolvable proactive outreach does not create appointment/travel records.
      console.log(`[WorldPhone] proactive outreach: recipient unresolved — no action taken`);
    }
  }

  return {
    responseText: modifiedResponseText,
    worldPhoneSendResult,
    proactiveSendResult,
  };
}