import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

/**
 * SLEEP MAINTENANCE CLEANUP
 * 
 * Runs when character wakes from sleep.
 * Purpose: daily lifecycle reset and stale state cleanup.
 * 
 * Tasks:
 * 1. Clear stale current_activity (only during active chat, regenerate via narrative otherwise)
 * 2. Clear stale travel_status and travel_destination_location_id if travel is complete
 * 3. Verify character is home after sleep
 * 4. Mark day as fresh (for day boundary logic)
 * 
 * Triggered by: character wake-up (resolved_presence_status changes from sleeping/napping to awake)
 */

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const body = await req.json().catch(() => ({}));
    const characterId = body.characterId;

    if (!characterId) {
      return Response.json({ error: 'Missing characterId' }, { status: 400 });
    }

    let char;
    try {
      const result = await base44.entities.Character.filter({ id: characterId });
      char = result[0];
    } catch {
      const result = await base44.asServiceRole.entities.Character.filter({ id: characterId });
      char = result[0];
    }

    if (!char) {
      return Response.json({ error: 'Character not found' }, { status: 404 });
    }

    // Only process if character is waking from sleep
    const wasAsleep = ['sleeping', 'napping'].includes(char.resolved_presence_status);
    if (!wasAsleep) {
      return Response.json({ success: false, reason: 'character_not_sleeping' });
    }

    const nowET = new Date(new Date().toLocaleString('en-US', { timeZone: 'America/New_York' }));
    const nowIso = nowET.toISOString();
    const wasActualSleep = char.resolved_presence_status === 'sleeping';
    const wasNap = char.resolved_presence_status === 'napping';

    // ── 6-HOUR MINIMUM SLEEP GUARD ───────────────────────────────────────────
    // sleepMaintenanceCleanup wakes the character unconditionally. That is only valid
    // if the character has slept at least 6 hours (the established minimum for
    // active_created_characters). Without this guard, any external caller (UI, scene exit,
    // scheduler) could trigger a premature wake.
    //
    // EXCEPTIONS: Medical emergency (health ≤ 15), or this is a nap (naps are short by design).
    //
    // If called before 6h without a valid override, refuse the wake and return a guard response.
    if (wasActualSleep && !wasNap) {
      const sleepStart = char.last_sleep_start;
      if (sleepStart) {
        const elapsedSleepHours = (nowET.getTime() - new Date(sleepStart).getTime()) / 3_600_000;
        const isMedicalEmergency = (char.health_value ?? 80) <= 15;
        if (elapsedSleepHours < 6 && !isMedicalEmergency) {
          console.log(`[sleepMaintenanceCleanup] 6H_GUARD: ${char.name} slept ${elapsedSleepHours.toFixed(2)}h < 6h — refusing premature wake`);
          return Response.json({
            success: false,
            reason: '6h_sleep_minimum_guard',
            character: char.name,
            elapsed_sleep_hours: Math.round(elapsedSleepHours * 100) / 100,
            message: `Character must sleep at least 6 hours. Only ${elapsedSleepHours.toFixed(2)}h elapsed. Call again after ${(6 - elapsedSleepHours).toFixed(2)} more hours.`,
          });
        }
      }
    }

    const cleanupPayload = {
      // Clear stale activity — will be regenerated by next narrative cycle
      current_activity: null,
      
      // Clear stale travel if destination is unreachable or null
      travel_status: char.travel_destination_location_id ? char.travel_status : 'not_traveling',
      travel_destination_location_id: char.travel_destination_location_id,
      
      // Mark as awake and at home (character should be home after sleep)
      resolved_presence_status: 'home',
      resolved_location_type: 'home',
      resolved_source_reason: 'sleep_cycle_complete',
      resolved_last_updated_at: nowIso,
    };
    if (wasActualSleep) {
      cleanupPayload.last_wake_time = nowIso;
    }
    // Nap wake does NOT write last_wake_time.
    if (!wasActualSleep && !wasNap) {
      base44.asServiceRole.entities.LifeEvent.create({
        character_id: characterId,
        character_name: char.name,
        event_type: 'medical_event',
        valence: 'neutral',
        severity: 'minor',
        title: 'Unknown sleep state cleared — cannot classify wake type',
        description: `sleepMaintenanceCleanup woke ${char.name} from prior presence "${char.resolved_presence_status}". Cannot determine if this was actual sleep or nap wake. last_wake_time NOT written.`,
        emotional_impact: 'system diagnostic',
        triggered_by: 'life_simulation',
        timestamp: nowIso,
        context_tags: ['missing_timestamp', 'unknown_sleep_state', 'sleepMaintenanceCleanup'],
      }).catch(() => {});
    }

    // Only update resolved location if not already home
    if (char.resolved_current_location_id !== char.current_home_location_id) {
      cleanupPayload.resolved_current_location_id = char.current_home_location_id;
      const homeLocations = [];
      try {
        const locs = await base44.entities.LocationReference.filter({ id: char.current_home_location_id });
        if (locs.length > 0) {
          cleanupPayload.resolved_current_location_name = locs[0].name;
        }
      } catch {
        // If fetch fails, use default name
        cleanupPayload.resolved_current_location_name = 'Home';
      }
    }

    try {
      await base44.entities.Character.update(characterId, cleanupPayload);
    } catch {
      await base44.asServiceRole.entities.Character.update(characterId, cleanupPayload);
    }

    return Response.json({
      success: true,
      character: char.name,
      cleared_stale_activity: true,
      verified_at_home: char.resolved_current_location_id === char.current_home_location_id,
      timestamp: new Date().toISOString(),
    });

  } catch (error) {
    console.error('[sleepMaintenanceCleanup]', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});