import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

/**
 * SLEEP MAINTENANCE CLEANUP
 * 
 * Runs when character wakes from sleep.
 * Purpose: daily lifecycle reset and stale state cleanup.
 * 
 * Tasks:
 * 1. Clear stale current_activity (only during active chat, regenerate via narrative otherwise)
 * 2. Clear stale travel_status and travel_destination_location_id if travel is complete
 * 3. Verify character is home after sleep
 * 4. Mark day as fresh (for day boundary logic)
 * 
 * Triggered by: character wake-up (resolved_presence_status changes from sleeping/napping to awake)
 */

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const body = await req.json().catch(() => ({}));
    const characterId = body.characterId;

    if (!characterId) {
      return Response.json({ error: 'Missing characterId' }, { status: 400 });
    }

    let char;
    try {
      const result = await base44.entities.Character.filter({ id: characterId });
      char = result[0];
    } catch {
      const result = await base44.asServiceRole.entities.Character.filter({ id: characterId });
      char = result[0];
    }

    if (!char) {
      return Response.json({ error: 'Character not found' }, { status: 404 });
    }

    // Only process if character is waking from sleep
    const wasAsleep = ['sleeping', 'napping'].includes(char.resolved_presence_status);
    if (!wasAsleep) {
      return Response.json({ success: false, reason: 'character_not_sleeping' });
    }

    const cleanupPayload = {
      // Clear stale activity — will be regenerated by next narrative cycle
      current_activity: null,
      
      // Clear stale travel if destination is unreachable or null
      travel_status: char.travel_destination_location_id ? char.travel_status : 'not_traveling',
      travel_destination_location_id: char.travel_destination_location_id,
      
      // Mark as awake and at home (character should be home after sleep)
      resolved_presence_status: 'home',
      resolved_location_type: 'home',
      resolved_source_reason: 'sleep_cycle_complete',
      resolved_last_updated_at: new Date().toISOString(),
    };

    // Only update resolved location if not already home
    if (char.resolved_current_location_id !== char.current_home_location_id) {
      cleanupPayload.resolved_current_location_id = char.current_home_location_id;
      const homeLocations = [];
      try {
        const locs = await base44.entities.LocationReference.filter({ id: char.current_home_location_id });
        if (locs.length > 0) {
          cleanupPayload.resolved_current_location_name = locs[0].name;
        }
      } catch {
        // If fetch fails, use default name
        cleanupPayload.resolved_current_location_name = 'Home';
      }
    }

    try {
      await base44.entities.Character.update(characterId, cleanupPayload);
    } catch {
      await base44.asServiceRole.entities.Character.update(characterId, cleanupPayload);
    }

    return Response.json({
      success: true,
      character: char.name,
      cleared_stale_activity: true,
      verified_at_home: char.resolved_current_location_id === char.current_home_location_id,
      timestamp: new Date().toISOString(),
    });

  } catch (error) {
    console.error('[sleepMaintenanceCleanup]', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});